# Generated by Django 5.0.6 on 2025-02-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='emotion_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
