# Generated by Django 5.0.6 on 2025-04-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmeeting',
            name='therapist_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
    ]
